---

- name: Create parameters
  template:
    src: templates/azuredeploy.parameters.j2
    dest: "azuredeploy.parameters.json"


#Create or update a Dashboard using parameter and template links
- name: Create Azure Deploy
  hosts: localhost
  tasks:
   - azure.azcollection.azure_rm_deployment:
      resource_group: atDashboardTestRG3
      name: atDashboardDeployment3
      parameters:
       dashboardname:
         value: dashboardansible-wip-json        
      template_link: 'https://raw.githubusercontent.com/tiwariashwanth/AST-Ansible-Dashboard/main/WIP-17Aug/dashboard-wip-json/sql-ansible-test.json'
 

- name: Output
  debug:
    msg: "{{ deploy.stdout }}"